/*    ==Parâmetros de Script==

    Edição do Mecanismo de Banco de Dados de Origem : Edição do Banco de Dados SQL do Microsoft Azure
    Tipo do Mecanismo de Banco de Dados de Origem : Banco de Dados SQL do Microsoft Azure

    Edição de Mecanismo de Banco de Dados de Destino : Edição do Banco de Dados SQL do Microsoft Azure
    Tipo de Mecanismo de Banco de Dados de Destino : Banco de Dados SQL do Microsoft Azure
*/

/****** Object:  UserDefinedFunction [dbo].[FUNC_SOMENTE_LETRAS]    Script Date: 09/12/2019 11:28:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE FUNCTION [dbo].[FUNC_SOMENTE_LETRAS] ( @TEXTO VARCHAR (5000))
RETURNS VARCHAR (5000)
AS
BEGIN
DECLARE @LETRAS VARCHAR(28)
DECLARE @QTD_TEXTO INT
DECLARE @CONTADOR INT
DECLARE @QTD INT
DECLARE @CONT INT
DECLARE @CONT_C INT
DECLARE @LETRA_ANT NVARCHAR(1)
DECLARE @LETRA_T NVARCHAR(1)
DECLARE @LETRA_C NVARCHAR(1)
DECLARE @RESULTADO VARCHAR(5000)
SET @LETRAS = 'ABCDEFGHIJKLMNOPQRSTUVXZWY ';

SET @QTD_TEXTO = (SELECT LEN(@TEXTO)) + 1
SET @CONTADOR = 0
SET @RESULTADO = ''
SET @LETRA_ANT = (SELECT SUBSTRING(@TEXTO,1,1))
INICIO:
WHILE @CONTADOR < @QTD_TEXTO
BEGIN
SET @CONTADOR = @CONTADOR + 1
SET @LETRA_T = (SELECT SUBSTRING(@TEXTO,@CONTADOR,1))
SET @CONT = (SELECT LEN(@LETRAS)) + 1
SET @QTD = 0
WHILE @QTD < @CONT
BEGIN
SET @QTD = @QTD + 1
SET @LETRA_C = (SELECT SUBSTRING(@LETRAS,@QTD,1))
IF @LETRA_C = @LETRA_T
BEGIN
IF @LETRA_ANT = ''
AND @LETRA_T = ''
BEGIN
GOTO INICIO
END
ELSE
BEGIN
SET @RESULTADO = @RESULTADO + (SELECT SUBSTRING(@LETRAS,@QTD,1))
SET @LETRA_ANT = @LETRA_T
GOTO INICIO
END
END
END
END

RETURN ( UPPER(@RESULTADO) )

END
GO


